---
- name: Install dependencies for rbenv
  apt: name={{ item }} state=latest
  with_items:
    - git

- name: Install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Eval rbenv init in ~/.profile
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'

- name: Install dependencies for ruby-build (see. https://github.com/sstephenson/ruby-build/wiki)
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: Install ruby-build as rbenv plugin
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Check if version is installed ruby
  shell: "/root/.rbenv/bin/rbenv versions | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: Install ruby
  command: "/root/.rbenv/bin/rbenv install {{ rbenv_ruby_version }}"
  when: rbenv_check_install|failed

- name: Check if version is the default ruby version
  shell: "/root/.rbenv/bin/rbenv version | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes

- name: Set default ruby version
  command: "/root/.rbenv/bin/rbenv global {{ rbenv_ruby_version }}"
  when: rbenv_check_default|failed

- name: Set ruby path
  lineinfile: >
    dest="/root/.bashrc"
    line="alias ruby='/root/.rbenv/shims/ruby'"
